ALTER TABLE assets
    ADD COLUMN IF NOT EXISTS ticker TEXT NOT NULL DEFAULT 'UNKNOWN',
    ADD COLUMN IF NOT EXISTS asset_type TEXT NOT NULL DEFAULT 'OTHER',
    ADD COLUMN IF NOT EXISTS quantity DOUBLE PRECISION NOT NULL DEFAULT 0;
