ALTER TABLE assets
    ADD COLUMN ticker VARCHAR(20) NOT NULL DEFAULT 'N/A',
    ADD COLUMN asset_type VARCHAR(50) NOT NULL DEFAULT 'OTHER',
    ADD COLUMN quantity DOUBLE PRECISION NOT NULL DEFAULT 0;
